// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT0gv3kiAB-OMLd9mz4S87OpGpT-dJnrw',
    appId: '1:479746642557:web:466dd02b5a0b21af551714',
    messagingSenderId: '479746642557',
    projectId: 'finstar-prod',
    authDomain: 'finstar-prod.firebaseapp.com',
    databaseURL: 'https://finstar-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finstar-prod.firebasestorage.app',
    measurementId: 'G-5RFB9W1T3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0gv3kiAB-OMLd9mz4S87OpGpT-dJnrw',
    appId: '1:479746642557:android:0b5d4bbebb49192f551714',
    messagingSenderId: '479746642557',
    projectId: 'finstar-prod',
    databaseURL: 'https://finstar-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finstar-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0gv3kiAB-OMLd9mz4S87OpGpT-dJnrw',
    appId: '1:479746642557:ios:6ea4c794dffd05fe551714',
    messagingSenderId: '479746642557',
    projectId: 'finstar-prod',
    databaseURL: 'https://finstar-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finstar-prod.firebasestorage.app',
    iosBundleId: 'com.finstar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0gv3kiAB-OMLd9mz4S87OpGpT-dJnrw',
    appId: '1:479746642557:ios:6ea4c794dffd05fe551714',
    messagingSenderId: '479746642557',
    projectId: 'finstar-prod',
    databaseURL: 'https://finstar-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finstar-prod.firebasestorage.app',
    iosBundleId: 'com.finstar.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT0gv3kiAB-OMLd9mz4S87OpGpT-dJnrw',
    appId: '1:479746642557:web:466dd02b5a0b21af551714',
    messagingSenderId: '479746642557',
    projectId: 'finstar-prod',
    databaseURL: 'https://finstar-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finstar-prod.firebasestorage.app',
    measurementId: 'G-5RFB9W1T3N',
  );
}
