import 'dart:math';

enum ScenarioCategory {
  food,
  entertainment,
  social,
  education,
  fashion,
  tech,
  transport,
  emergency,
  health,
  investment,
}

class DecisionImpact {
  final int happiness;
  final int investments;
  final int socialLife;
  final int discipline;
  final bool overspendFlag;

  DecisionImpact({
    required this.happiness,
    required this.investments,
    required this.socialLife,
    required this.discipline,
    required this.overspendFlag,
  });
}

class SpendingScenario {
  final String id;
  final String title;
  final String description;
  final int cost;
  final ScenarioCategory category;
  final String emoji;
  final DecisionImpact acceptImpact; // Swipe right / Accept
  final DecisionImpact declineImpact; // Swipe left / Decline
  final String acceptLabel;
  final String declineLabel;
  final String? consequence; // What happens if you accept
  final String? benefit; // What happens if you decline

  SpendingScenario({
    required this.id,
    required this.title,
    required this.description,
    required this.cost,
    required this.category,
    required this.emoji,
    required this.acceptImpact,
    required this.declineImpact,
    required this.acceptLabel,
    required this.declineLabel,
    this.consequence,
    this.benefit,
  });

  static List<SpendingScenario> getAllScenarios() {
    return [
      // FOOD & DINING (20 scenarios)
      SpendingScenario(
        id: 'food_1',
        title: 'Late Night Biryani Craving',
        description: 'It\'s 2 AM. You\'re studying and hungry. Zomato biryani costs ₹400 with delivery.',
        cost: 400,
        category: ScenarioCategory.food,
        emoji: '🍛',
        acceptImpact: DecisionImpact(happiness: 15, investments: -10, socialLife: 0, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Order it',
        declineLabel: 'Cook maggi',
        consequence: 'Satisfied but ₹400 gone',
        benefit: 'Saved money, ate healthy',
      ),

      SpendingScenario(
        id: 'food_2',
        title: 'Weekend Brunch Squad',
        description: 'Friends going to fancy cafe. Split bill will be ₹800 per person.',
        cost: 800,
        category: ScenarioCategory.food,
        emoji: '☕',
        acceptImpact: DecisionImpact(happiness: 20, investments: -15, socialLife: 15, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -10, investments: 15, socialLife: -8, discipline: 10, overspendFlag: false),
        acceptLabel: 'Join them',
        declineLabel: 'Skip this time',
        consequence: 'Great vibes, expensive',
        benefit: 'Saved money, some FOMO',
      ),

      SpendingScenario(
        id: 'food_3',
        title: 'Starbucks Study Session',
        description: 'Need a study spot. Starbucks coffee ₹350. Library is free.',
        cost: 350,
        category: ScenarioCategory.food,
        emoji: '☕',
        acceptImpact: DecisionImpact(happiness: 10, investments: -8, socialLife: 5, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 8, socialLife: 0, discipline: 12, overspendFlag: false),
        acceptLabel: 'Starbucks',
        declineLabel: 'Library',
        consequence: 'Aesthetic spot, costly',
        benefit: 'Saved money, focused better',
      ),

      SpendingScenario(
        id: 'food_4',
        title: 'Daily Boba Tea Habit',
        description: 'You get boba tea daily (₹250/day). That\'s ₹7,500/month!',
        cost: 7500,
        category: ScenarioCategory.food,
        emoji: '🧋',
        acceptImpact: DecisionImpact(happiness: 15, investments: -20, socialLife: 5, discipline: -20, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 20, socialLife: 0, discipline: 25, overspendFlag: false),
        acceptLabel: 'Keep habit',
        declineLabel: 'Cut to 1x/week',
        consequence: 'Daily joy, huge cost',
        benefit: 'Save ₹6000/month, discipline',
      ),

      SpendingScenario(
        id: 'food_5',
        title: 'Protein Powder',
        description: 'Premium whey protein: ₹3,500. You want to bulk up. Eggs cheaper.',
        cost: 3500,
        category: ScenarioCategory.food,
        emoji: '💪',
        acceptImpact: DecisionImpact(happiness: 12, investments: 10, socialLife: 0, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 5, investments: 15, socialLife: 0, discipline: 8, overspendFlag: false),
        acceptLabel: 'Buy protein',
        declineLabel: 'Natural foods',
        consequence: 'Convenient, investment in health',
        benefit: 'Cheaper, more effort',
      ),

      SpendingScenario(
        id: 'food_6',
        title: 'Swiggy One Membership',
        description: 'Annual membership: ₹1,499. Free delivery. You order 3x/month.',
        cost: 1499,
        category: ScenarioCategory.food,
        emoji: '🍕',
        acceptImpact: DecisionImpact(happiness: 8, investments: 5, socialLife: 0, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: 8, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Pay per order',
        consequence: 'Saves long-term if used',
        benefit: 'No commitment',
      ),

      SpendingScenario(
        id: 'food_7',
        title: 'Meal Prep Containers',
        description: 'Glass meal prep set: ₹2,000. Helps save money cooking in bulk.',
        cost: 2000,
        category: ScenarioCategory.food,
        emoji: '🍱',
        acceptImpact: DecisionImpact(happiness: 10, investments: 15, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -5, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Invest',
        declineLabel: 'Skip',
        consequence: 'Smart investment pays off',
        benefit: 'Continue daily spending',
      ),

      SpendingScenario(
        id: 'food_8',
        title: 'Street Food Splurge',
        description: 'Pani puri, chaat, rolls at food street: ₹300. Home food ready.',
        cost: 300,
        category: ScenarioCategory.food,
        emoji: '🥟',
        acceptImpact: DecisionImpact(happiness: 15, investments: -8, socialLife: 10, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 8, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Street food',
        declineLabel: 'Home food',
        consequence: 'Tasty, not healthy',
        benefit: 'Saved money, ate healthy',
      ),

      SpendingScenario(
        id: 'food_9',
        title: 'Pizza Party at Home',
        description: 'Order 2 large pizzas for ₹1,200. Friends coming over.',
        cost: 1200,
        category: ScenarioCategory.food,
        emoji: '🍕',
        acceptImpact: DecisionImpact(happiness: 20, investments: -12, socialLife: 18, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 5, investments: 12, socialLife: -5, discipline: 15, overspendFlag: false),
        acceptLabel: 'Order pizza',
        declineLabel: 'Cook together',
        consequence: 'Easy, expensive',
        benefit: 'Saved money, bonding while cooking',
      ),

      SpendingScenario(
        id: 'food_10',
        title: 'Energy Drink Addiction',
        description: 'You buy Red Bull daily (₹150/day) for energy. ₹4,500/month!',
        cost: 4500,
        category: ScenarioCategory.food,
        emoji: '⚡',
        acceptImpact: DecisionImpact(happiness: 8, investments: -18, socialLife: 0, discipline: -20, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 18, socialLife: 0, discipline: 25, overspendFlag: false),
        acceptLabel: 'Continue',
        declineLabel: 'Switch to coffee',
        consequence: 'Short energy, health cost',
        benefit: 'Save huge, healthier option',
      ),

      SpendingScenario(
        id: 'food_11',
        title: 'Burger King Coupon',
        description: 'Whopper meal on discount: ₹250. You just ate lunch.',
        cost: 250,
        category: ScenarioCategory.food,
        emoji: '🍔',
        acceptImpact: DecisionImpact(happiness: 8, investments: -10, socialLife: 0, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 18, overspendFlag: false),
        acceptLabel: 'Get it',
        declineLabel: 'Skip',
        consequence: 'Impulse buy, not needed',
        benefit: 'Resisted temptation',
      ),

      SpendingScenario(
        id: 'food_12',
        title: 'Premium Tea Subscription',
        description: 'Exotic tea subscription: ₹800/month. You love tea.',
        cost: 800,
        category: ScenarioCategory.food,
        emoji: '🍵',
        acceptImpact: DecisionImpact(happiness: 12, investments: -8, socialLife: 0, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 8, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Regular tea',
        consequence: 'Luxury, recurring cost',
        benefit: 'Regular tea works fine',
      ),

      SpendingScenario(
        id: 'food_13',
        title: 'Ice Cream After Breakup',
        description: 'Feeling sad. Ben & Jerry\'s pint costs ₹500.',
        cost: 500,
        category: ScenarioCategory.food,
        emoji: '🍦',
        acceptImpact: DecisionImpact(happiness: 10, investments: -10, socialLife: 0, discipline: -12, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Treat yourself',
        declineLabel: 'Deal with it',
        consequence: 'Temporary comfort',
        benefit: 'Process emotions, save money',
      ),

      SpendingScenario(
        id: 'food_14',
        title: 'Food Delivery vs Cooking',
        description: 'Tired after gym. Order healthy meal ₹450 or cook (₹150).',
        cost: 450,
        category: ScenarioCategory.food,
        emoji: '🥗',
        acceptImpact: DecisionImpact(happiness: 12, investments: -10, socialLife: 0, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 18, overspendFlag: false),
        acceptLabel: 'Order',
        declineLabel: 'Cook',
        consequence: 'Saves time, 3x cost',
        benefit: 'Learn cooking, save money',
      ),

      SpendingScenario(
        id: 'food_15',
        title: 'Coffee Machine',
        description: 'Espresso machine: ₹15,000. Save money vs daily cafe.',
        cost: 15000,
        category: ScenarioCategory.food,
        emoji: '☕',
        acceptImpact: DecisionImpact(happiness: 15, investments: 20, socialLife: 0, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -10, socialLife: 0, discipline: 0, overspendFlag: false),
        acceptLabel: 'Buy machine',
        declineLabel: 'Keep going to cafe',
        consequence: 'Big upfront, saves long-term',
        benefit: 'Social cafe time continues',
      ),

      SpendingScenario(
        id: 'food_16',
        title: 'Organic Groceries',
        description: 'Organic groceries cost 2x more. ₹2,000 extra per month.',
        cost: 2000,
        category: ScenarioCategory.food,
        emoji: '🥬',
        acceptImpact: DecisionImpact(happiness: 10, investments: 8, socialLife: 0, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 5, overspendFlag: false),
        acceptLabel: 'Go organic',
        declineLabel: 'Regular groceries',
        consequence: 'Health investment, pricey',
        benefit: 'Regular food is fine',
      ),

      SpendingScenario(
        id: 'food_17',
        title: 'Weekend Dining Out',
        description: 'Nice restaurant with family: ₹2,500 your share.',
        cost: 2500,
        category: ScenarioCategory.food,
        emoji: '🍽️',
        acceptImpact: DecisionImpact(happiness: 18, investments: -12, socialLife: 20, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 12, socialLife: -10, discipline: 10, overspendFlag: false),
        acceptLabel: 'Go out',
        declineLabel: 'Eat at home',
        consequence: 'Family time, expensive',
        benefit: 'Miss bonding, save money',
      ),

      SpendingScenario(
        id: 'food_18',
        title: 'Sushi First Time',
        description: 'Friends trying sushi. ₹1,800 per person. You\'re curious.',
        cost: 1800,
        category: ScenarioCategory.food,
        emoji: '🍣',
        acceptImpact: DecisionImpact(happiness: 15, investments: -12, socialLife: 12, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 12, socialLife: -8, discipline: 8, overspendFlag: false),
        acceptLabel: 'Try it',
        declineLabel: 'Skip',
        consequence: 'New experience, pricey',
        benefit: 'FOMO but saved',
      ),

      SpendingScenario(
        id: 'food_19',
        title: 'Birthday Cake Special Order',
        description: 'Custom cake for friend: ₹1,500. Regular cake is ₹500.',
        cost: 1500,
        category: ScenarioCategory.food,
        emoji: '🎂',
        acceptImpact: DecisionImpact(happiness: 15, investments: -10, socialLife: 18, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 5, investments: 10, socialLife: -5, discipline: 10, overspendFlag: false),
        acceptLabel: 'Custom cake',
        declineLabel: 'Regular cake',
        consequence: 'Friend happy, expensive',
        benefit: 'Good enough, saved',
      ),

      SpendingScenario(
        id: 'food_20',
        title: 'Cooking Class',
        description: 'Weekend cooking class: ₹3,000. Learn to cook healthy.',
        cost: 3000,
        category: ScenarioCategory.food,
        emoji: '👨‍🍳',
        acceptImpact: DecisionImpact(happiness: 12, investments: 20, socialLife: 8, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -10, socialLife: 0, discipline: -5, overspendFlag: false),
        acceptLabel: 'Take class',
        declineLabel: 'YouTube videos',
        consequence: 'Skill investment pays off',
        benefit: 'Free learning, need discipline',
      ),

      // ENTERTAINMENT (15 scenarios)
      SpendingScenario(
        id: 'ent_1',
        title: 'Concert Tickets',
        description: 'Favorite artist performing. Tickets ₹2,500. All friends going.',
        cost: 2500,
        category: ScenarioCategory.entertainment,
        emoji: '🎵',
        acceptImpact: DecisionImpact(happiness: 30, investments: -15, socialLife: 20, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -15, investments: 15, socialLife: -18, discipline: 12, overspendFlag: false),
        acceptLabel: 'Buy ticket',
        declineLabel: 'Watch stories',
        consequence: 'Epic memories, broke for week',
        benefit: 'Massive FOMO, savings intact',
      ),

      SpendingScenario(
        id: 'ent_2',
        title: 'Netflix Premium',
        description: 'Share Netflix Premium (₹650/month). Using free options now.',
        cost: 650,
        category: ScenarioCategory.entertainment,
        emoji: '🎬',
        acceptImpact: DecisionImpact(happiness: 12, investments: -10, socialLife: 5, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 10, socialLife: 0, discipline: 12, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Stay free',
        consequence: '4K streaming, recurring cost',
        benefit: 'Saving ₹7800/year',
      ),

      SpendingScenario(
        id: 'ent_3',
        title: 'Gaming Tournament Entry',
        description: 'BGMI tournament: ₹500 entry. Prize ₹50,000. You\'re decent.',
        cost: 500,
        category: ScenarioCategory.entertainment,
        emoji: '🎮',
        acceptImpact: DecisionImpact(happiness: 15, investments: -5, socialLife: 10, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 5, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Enter',
        declineLabel: 'Play casually',
        consequence: 'Fun competition, gambling mindset',
        benefit: 'Avoided risk',
      ),

      SpendingScenario(
        id: 'ent_4',
        title: 'Spotify Premium',
        description: 'Spotify Premium: ₹119/month. Using YouTube free with ads.',
        cost: 119,
        category: ScenarioCategory.entertainment,
        emoji: '🎵',
        acceptImpact: DecisionImpact(happiness: 10, investments: -5, socialLife: 0, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -3, investments: 5, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Premium',
        declineLabel: 'Free version',
        consequence: 'Ad-free, recurring cost',
        benefit: 'Save ₹1428/year, tolerate ads',
      ),

      SpendingScenario(
        id: 'ent_5',
        title: 'Movie Theater Experience',
        description: 'Marvel movie in theater: ₹400. Streams on Disney+ in 45 days.',
        cost: 400,
        category: ScenarioCategory.entertainment,
        emoji: '🎬',
        acceptImpact: DecisionImpact(happiness: 18, investments: -8, socialLife: 10, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 8, socialLife: 0, discipline: 12, overspendFlag: false),
        acceptLabel: 'Theater',
        declineLabel: 'Wait for OTT',
        consequence: 'Big screen experience, pricey',
        benefit: 'Save money, spoiler risk',
      ),

      SpendingScenario(
        id: 'ent_6',
        title: 'Stand-up Comedy Show',
        description: 'Favorite comedian live: ₹1,200. Can watch Netflix specials.',
        cost: 1200,
        category: ScenarioCategory.entertainment,
        emoji: '🎤',
        acceptImpact: DecisionImpact(happiness: 20, investments: -10, socialLife: 15, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 10, socialLife: -8, discipline: 8, overspendFlag: false),
        acceptLabel: 'Book ticket',
        declineLabel: 'Netflix special',
        consequence: 'Live experience, memorable',
        benefit: 'Same jokes, no atmosphere',
      ),

      SpendingScenario(
        id: 'ent_7',
        title: 'Gaming PC Upgrade',
        description: 'RTX 4060 GPU: ₹35,000. Current GPU handles medium settings.',
        cost: 35000,
        category: ScenarioCategory.tech,
        emoji: '🎮',
        acceptImpact: DecisionImpact(happiness: 25, investments: -20, socialLife: 5, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -10, investments: 20, socialLife: 0, discipline: 20, overspendFlag: false),
        acceptLabel: 'Upgrade',
        declineLabel: 'Current is fine',
        consequence: 'Ultra settings, huge cost',
        benefit: 'Functional setup, save big',
      ),

      SpendingScenario(
        id: 'ent_8',
        title: 'Board Game Night',
        description: 'Friends buying board game: ₹2,500. Chip in ₹500.',
        cost: 500,
        category: ScenarioCategory.entertainment,
        emoji: '🎲',
        acceptImpact: DecisionImpact(happiness: 12, investments: -5, socialLife: 18, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: 5, socialLife: -10, discipline: 8, overspendFlag: false),
        acceptLabel: 'Chip in',
        declineLabel: 'Skip',
        consequence: 'Fun nights ahead, shared cost',
        benefit: 'Miss bonding time',
      ),

      SpendingScenario(
        id: 'ent_9',
        title: 'PlayStation 5',
        description: 'PS5 available: ₹50,000. You mostly game on PC.',
        cost: 50000,
        category: ScenarioCategory.tech,
        emoji: '🎮',
        acceptImpact: DecisionImpact(happiness: 30, investments: -25, socialLife: 10, discipline: -20, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -12, investments: 25, socialLife: 0, discipline: 25, overspendFlag: false),
        acceptLabel: 'Get console',
        declineLabel: 'Stick to PC',
        consequence: 'Exclusive games, huge cost',
        benefit: 'Avoided duplicate expense',
      ),

      SpendingScenario(
        id: 'ent_10',
        title: 'Music Festival Pass',
        description: '3-day music festival: ₹5,000. Camping, multiple artists.',
        cost: 5000,
        category: ScenarioCategory.entertainment,
        emoji: '🎪',
        acceptImpact: DecisionImpact(happiness: 35, investments: -18, socialLife: 25, discipline: -12, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -15, investments: 18, socialLife: -15, discipline: 15, overspendFlag: false),
        acceptLabel: 'Go',
        declineLabel: 'Skip',
        consequence: 'Unforgettable experience',
        benefit: 'Huge FOMO, money saved',
      ),

      SpendingScenario(
        id: 'ent_11',
        title: 'YouTube Premium Family',
        description: 'YouTube Premium family plan: ₹189/month. No ads, downloads.',
        cost: 189,
        category: ScenarioCategory.entertainment,
        emoji: '📺',
        acceptImpact: DecisionImpact(happiness: 8, investments: -5, socialLife: 0, discipline: -3, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -3, investments: 5, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Free with ads',
        consequence: 'Convenient, yearly ₹2268',
        benefit: 'Tolerate ads, save money',
      ),

      SpendingScenario(
        id: 'ent_12',
        title: 'Cricket Match Tickets',
        description: 'IPL final tickets: ₹3,500. Watch on TV free.',
        cost: 3500,
        category: ScenarioCategory.entertainment,
        emoji: '🏏',
        acceptImpact: DecisionImpact(happiness: 25, investments: -15, socialLife: 20, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 15, socialLife: -5, discipline: 12, overspendFlag: false),
        acceptLabel: 'Go to stadium',
        declineLabel: 'Watch on TV',
        consequence: 'Live atmosphere, expensive',
        benefit: 'Comfortable home, free',
      ),

      SpendingScenario(
        id: 'ent_13',
        title: 'Gaming Chair',
        description: 'Ergonomic gaming chair: ₹18,000. Current chair is ok.',
        cost: 18000,
        category: ScenarioCategory.tech,
        emoji: '🪑',
        acceptImpact: DecisionImpact(happiness: 15, investments: 8, socialLife: 0, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Buy chair',
        declineLabel: 'Current works',
        consequence: 'Comfort investment, health',
        benefit: 'Save money, manage posture',
      ),

      SpendingScenario(
        id: 'ent_14',
        title: 'Escape Room Experience',
        description: 'Escape room with friends: ₹800 per person.',
        cost: 800,
        category: ScenarioCategory.entertainment,
        emoji: '🔐',
        acceptImpact: DecisionImpact(happiness: 18, investments: -8, socialLife: 20, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 8, socialLife: -12, discipline: 10, overspendFlag: false),
        acceptLabel: 'Join',
        declineLabel: 'Skip',
        consequence: 'Team bonding, fun',
        benefit: 'Miss experience, save money',
      ),

      SpendingScenario(
        id: 'ent_15',
        title: 'Guitar Lessons',
        description: 'Monthly guitar lessons: ₹2,000. Learn from YouTube free.',
        cost: 2000,
        category: ScenarioCategory.education,
        emoji: '🎸',
        acceptImpact: DecisionImpact(happiness: 15, investments: 15, socialLife: 5, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 5, investments: -5, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Take lessons',
        declineLabel: 'Self-teach',
        consequence: 'Structured learning, investment',
        benefit: 'Free but need discipline',
      ),

      // SOCIAL LIFE (15 scenarios)
      SpendingScenario(
        id: 'social_1',
        title: 'Friend\'s Birthday Gift',
        description: 'Close friend\'s birthday. Group gift ₹1,200 per person.',
        cost: 1200,
        category: ScenarioCategory.social,
        emoji: '🎁',
        acceptImpact: DecisionImpact(happiness: 15, investments: -10, socialLife: 25, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -10, investments: 10, socialLife: -20, discipline: 10, overspendFlag: false),
        acceptLabel: 'Contribute',
        declineLabel: 'Personal gift',
        consequence: 'Friend happy, you\'re broke',
        benefit: 'Awkward explanation needed',
      ),

      SpendingScenario(
        id: 'social_2',
        title: 'Goa Trip with Squad',
        description: '3-day Goa trip. Your share: ₹8,000 (travel, stay, food).',
        cost: 8000,
        category: ScenarioCategory.social,
        emoji: '🏖️',
        acceptImpact: DecisionImpact(happiness: 35, investments: -20, socialLife: 30, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -15, investments: 20, socialLife: -25, discipline: 20, overspendFlag: false),
        acceptLabel: 'I\'m in!',
        declineLabel: 'Maybe next time',
        consequence: 'Lifetime memories, empty wallet',
        benefit: 'Huge FOMO but responsible',
      ),

      SpendingScenario(
        id: 'social_3',
        title: 'Club Entry Night',
        description: 'Friends going to club. Entry + 2 drinks: ₹1,800.',
        cost: 1800,
        category: ScenarioCategory.social,
        emoji: '🎉',
        acceptImpact: DecisionImpact(happiness: 15, investments: -15, socialLife: 22, discipline: -12, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 15, socialLife: -18, discipline: 15, overspendFlag: false),
        acceptLabel: 'Join squad',
        declineLabel: 'Stay home',
        consequence: 'Night out, expensive drinks',
        benefit: 'Save money, face FOMO',
      ),

      SpendingScenario(
        id: 'social_4',
        title: 'Gym Buddy Membership',
        description: 'Friend wants gym partner. Annual: ₹15,000. Can workout home.',
        cost: 15000,
        category: ScenarioCategory.social,
        emoji: '🏋️',
        acceptImpact: DecisionImpact(happiness: 15, investments: 15, socialLife: 20, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: 5, socialLife: -12, discipline: -8, overspendFlag: false),
        acceptLabel: 'Join gym',
        declineLabel: 'Home workout',
        consequence: 'Motivation + equipment',
        benefit: 'Free but need discipline',
      ),

      SpendingScenario(
        id: 'social_5',
        title: 'Secret Santa Budget',
        description: 'Office Secret Santa: ₹1,500 limit. Everyone will splurge.',
        cost: 1500,
        category: ScenarioCategory.social,
        emoji: '🎁',
        acceptImpact: DecisionImpact(happiness: 10, investments: -10, socialLife: 18, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 10, socialLife: -15, discipline: 10, overspendFlag: false),
        acceptLabel: 'Full budget',
        declineLabel: 'Cheap gift',
        consequence: 'Social acceptance, costly',
        benefit: 'Judged but saved money',
      ),

      SpendingScenario(
        id: 'social_6',
        title: 'Pet Adoption',
        description: 'Adopt puppy: ₹5,000 initial + ₹3,000/month maintenance.',
        cost: 8000,
        category: ScenarioCategory.social,
        emoji: '🐕',
        acceptImpact: DecisionImpact(happiness: 30, investments: -15, socialLife: 10, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -12, investments: 15, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Adopt',
        declineLabel: 'Wait',
        consequence: 'Companionship, big commitment',
        benefit: 'Not ready financially',
      ),

      SpendingScenario(
        id: 'social_7',
        title: 'Dating App Premium',
        description: 'Tinder Gold: ₹1,099/month. See who likes you.',
        cost: 1099,
        category: ScenarioCategory.social,
        emoji: '💖',
        acceptImpact: DecisionImpact(happiness: 10, investments: -12, socialLife: 12, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 12, socialLife: -5, discipline: 15, overspendFlag: false),
        acceptLabel: 'Go premium',
        declineLabel: 'Free version',
        consequence: 'More matches, recurring cost',
        benefit: 'Free works, save money',
      ),

      SpendingScenario(
        id: 'social_8',
        title: 'Team Dinner Split',
        description: 'Team dinner after project. Split ₹1,000 each.',
        cost: 1000,
        category: ScenarioCategory.social,
        emoji: '🍽️',
        acceptImpact: DecisionImpact(happiness: 15, investments: -10, socialLife: 20, discipline: -5, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 10, socialLife: -15, discipline: 12, overspendFlag: false),
        acceptLabel: 'Join',
        declineLabel: 'Skip',
        consequence: 'Team bonding, expensive',
        benefit: 'Miss bonding, save money',
      ),

      SpendingScenario(
        id: 'social_9',
        title: 'Wedding Gift for Cousin',
        description: 'Cousin\'s wedding. Gift ₹5,000 or ₹2,000?',
        cost: 5000,
        category: ScenarioCategory.social,
        emoji: '💍',
        acceptImpact: DecisionImpact(happiness: 12, investments: -12, socialLife: 20, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 5, investments: 12, socialLife: -8, discipline: 10, overspendFlag: false),
        acceptLabel: '₹5,000',
        declineLabel: '₹2,000',
        consequence: 'Generous, expensive',
        benefit: 'Still good, saved money',
      ),

      SpendingScenario(
        id: 'social_10',
        title: 'Roommate Moving Out',
        description: 'Roommate needs security deposit help: ₹10,000 loan.',
        cost: 10000,
        category: ScenarioCategory.social,
        emoji: '🤝',
        acceptImpact: DecisionImpact(happiness: 10, investments: -15, socialLife: 25, discipline: 5, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: 15, socialLife: -18, discipline: 15, overspendFlag: false),
        acceptLabel: 'Lend money',
        declineLabel: 'Can\'t help',
        consequence: 'Good friend, risk not getting back',
        benefit: 'Awkward but financially safe',
      ),

      SpendingScenario(
        id: 'social_11',
        title: 'House Party Hosting',
        description: 'Host house party. Drinks + snacks: ₹3,000.',
        cost: 3000,
        category: ScenarioCategory.social,
        emoji: '🎉',
        acceptImpact: DecisionImpact(happiness: 20, investments: -15, socialLife: 25, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 15, socialLife: -12, discipline: 15, overspendFlag: false),
        acceptLabel: 'Host it',
        declineLabel: 'Skip',
        consequence: 'Great host, expensive',
        benefit: 'Save money, miss fun',
      ),

      SpendingScenario(
        id: 'social_12',
        title: 'Destination Bachelor Party',
        description: 'Best friend\'s bachelor party in Bangkok: ₹25,000.',
        cost: 25000,
        category: ScenarioCategory.social,
        emoji: '✈️',
        acceptImpact: DecisionImpact(happiness: 35, investments: -25, socialLife: 35, discipline: -18, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -20, investments: 25, socialLife: -30, discipline: 25, overspendFlag: false),
        acceptLabel: 'Go',
        declineLabel: 'Can\'t afford',
        consequence: 'Once in lifetime, huge cost',
        benefit: 'Miss major event, financially safe',
      ),

      SpendingScenario(
        id: 'social_13',
        title: 'Photography Workshop',
        description: 'Weekend photography workshop: ₹4,000. Meet like-minded people.',
        cost: 4000,
        category: ScenarioCategory.education,
        emoji: '📸',
        acceptImpact: DecisionImpact(happiness: 15, investments: 15, socialLife: 15, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -5, socialLife: -10, discipline: -5, overspendFlag: false),
        acceptLabel: 'Join',
        declineLabel: 'Learn online',
        consequence: 'Skill + networking',
        benefit: 'Free learning, no connections',
      ),

      SpendingScenario(
        id: 'social_14',
        title: 'Volunteer Trip',
        description: 'Week-long volunteer trip: ₹6,000. Meaningful experience.',
        cost: 6000,
        category: ScenarioCategory.social,
        emoji: '🤲',
        acceptImpact: DecisionImpact(happiness: 25, investments: 5, socialLife: 20, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: 10, socialLife: -10, discipline: 5, overspendFlag: false),
        acceptLabel: 'Go',
        declineLabel: 'Local volunteer',
        consequence: 'Life-changing experience',
        benefit: 'Local helps too, saves money',
      ),

      SpendingScenario(
        id: 'social_15',
        title: 'Friend\'s Startup Investment',
        description: 'Friend\'s startup needs investors: ₹20,000 for 2% equity.',
        cost: 20000,
        category: ScenarioCategory.investment,
        emoji: '🚀',
        acceptImpact: DecisionImpact(happiness: 10, investments: 25, socialLife: 20, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -10, socialLife: -15, discipline: 15, overspendFlag: false),
        acceptLabel: 'Invest',
        declineLabel: 'Pass',
        consequence: 'Support friend, high risk',
        benefit: 'Safe money, strain friendship',
      ),

      // EDUCATION & SKILLS (15 scenarios)
      SpendingScenario(
        id: 'edu_1',
        title: 'Web Dev Course',
        description: 'Udemy Web Dev course: ₹1,500. Could freelance ₹10k/month.',
        cost: 1500,
        category: ScenarioCategory.education,
        emoji: '💻',
        acceptImpact: DecisionImpact(happiness: 10, investments: 25, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -10, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Invest',
        declineLabel: 'Free tutorials',
        consequence: 'Structured learning',
        benefit: 'Free but scattered',
      ),

      SpendingScenario(
        id: 'edu_2',
        title: 'AWS Certification',
        description: 'AWS exam fee: ₹4,000. Boosts resume but not mandatory.',
        cost: 4000,
        category: ScenarioCategory.education,
        emoji: '📜',
        acceptImpact: DecisionImpact(happiness: 12, investments: 25, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -8, socialLife: 0, discipline: -5, overspendFlag: false),
        acceptLabel: 'Take exam',
        declineLabel: 'Skip for now',
        consequence: 'Career boost, expensive bet',
        benefit: 'Focus on free learning',
      ),

      SpendingScenario(
        id: 'edu_3',
        title: 'Physical Books vs PDFs',
        description: 'Course books: ₹2,000. PDFs available free (gray area).',
        cost: 2000,
        category: ScenarioCategory.education,
        emoji: '📚',
        acceptImpact: DecisionImpact(happiness: 10, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -5, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Buy books',
        declineLabel: 'Use PDFs',
        consequence: 'Better focus, supports authors',
        benefit: 'Free but screen strain',
      ),

      SpendingScenario(
        id: 'edu_4',
        title: 'Graphic Design Course',
        description: 'Adobe course: ₹3,000. Freelance ₹500-1000/project.',
        cost: 3000,
        category: ScenarioCategory.education,
        emoji: '🎨',
        acceptImpact: DecisionImpact(happiness: 12, investments: 28, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -12, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Learn skill',
        declineLabel: 'YouTube free',
        consequence: 'Structured, investment',
        benefit: 'Self-taught but scattered',
      ),

      SpendingScenario(
        id: 'edu_5',
        title: 'LeetCode Premium',
        description: 'LeetCode Premium: ₹2,500/year. Company interview questions.',
        cost: 2500,
        category: ScenarioCategory.education,
        emoji: '💻',
        acceptImpact: DecisionImpact(happiness: 8, investments: 22, socialLife: 0, discipline: 18, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -8, socialLife: 0, discipline: -5, overspendFlag: false),
        acceptLabel: 'Premium',
        declineLabel: 'Free tier',
        consequence: 'Interview edge, yearly cost',
        benefit: 'Free is usually enough',
      ),

      SpendingScenario(
        id: 'edu_6',
        title: 'Tech Conference',
        description: 'Tech conference: ₹5,000. Networking but can watch online.',
        cost: 5000,
        category: ScenarioCategory.education,
        emoji: '🎫',
        acceptImpact: DecisionImpact(happiness: 15, investments: 20, socialLife: 18, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -8, socialLife: -10, discipline: 5, overspendFlag: false),
        acceptLabel: 'Attend',
        declineLabel: 'Watch online',
        consequence: 'Network + learn, pricey',
        benefit: 'Miss connections, free',
      ),

      SpendingScenario(
        id: 'edu_7',
        title: 'Duolingo Plus',
        description: 'Duolingo Plus: ₹699/month. Learning Spanish. Free has limits.',
        cost: 699,
        category: ScenarioCategory.education,
        emoji: '🗣️',
        acceptImpact: DecisionImpact(happiness: 10, investments: 15, socialLife: 0, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -3, investments: -5, socialLife: 0, discipline: -8, overspendFlag: false),
        acceptLabel: 'Go premium',
        declineLabel: 'Free version',
        consequence: 'Unlimited, monthly fee',
        benefit: 'Ads but saves ₹8388/year',
      ),

      SpendingScenario(
        id: 'edu_8',
        title: 'Laptop for Coding',
        description: 'MacBook Air M2: ₹95,000. Current laptop works but slow.',
        cost: 95000,
        category: ScenarioCategory.tech,
        emoji: '💻',
        acceptImpact: DecisionImpact(happiness: 20, investments: 25, socialLife: 5, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -8, investments: -15, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Buy MacBook',
        declineLabel: 'Use current',
        consequence: 'Career investment, huge cost',
        benefit: 'Current works, save huge',
      ),

      SpendingScenario(
        id: 'edu_9',
        title: 'English Speaking Course',
        description: 'English speaking course: ₹5,000. Improves communication.',
        cost: 5000,
        category: ScenarioCategory.education,
        emoji: '🎤',
        acceptImpact: DecisionImpact(happiness: 12, investments: 22, socialLife: 15, discipline: 18, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -10, socialLife: -8, discipline: -10, overspendFlag: false),
        acceptLabel: 'Take course',
        declineLabel: 'Practice free',
        consequence: 'Confidence boost, investment',
        benefit: 'Free practice, need discipline',
      ),

      SpendingScenario(
        id: 'edu_10',
        title: 'Stock Market Course',
        description: 'Stock market basics course: ₹3,500. Start investing smart.',
        cost: 3500,
        category: ScenarioCategory.education,
        emoji: '📈',
        acceptImpact: DecisionImpact(happiness: 10, investments: 30, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -15, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Learn investing',
        declineLabel: 'YouTube videos',
        consequence: 'Smart money moves',
        benefit: 'Free but overwhelming info',
      ),

      SpendingScenario(
        id: 'edu_11',
        title: 'Exam Preparation App',
        description: 'Unacademy Plus: ₹999/month. Preparing for competitive exam.',
        cost: 999,
        category: ScenarioCategory.education,
        emoji: '📝',
        acceptImpact: DecisionImpact(happiness: 8, investments: 18, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -10, socialLife: 0, discipline: -12, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Free content',
        consequence: 'Structured prep, recurring cost',
        benefit: 'Free but less organized',
      ),

      SpendingScenario(
        id: 'edu_12',
        title: 'Masterclass Subscription',
        description: 'Masterclass annual: ₹10,000. Learn from experts.',
        cost: 10000,
        category: ScenarioCategory.education,
        emoji: '🎓',
        acceptImpact: DecisionImpact(happiness: 15, investments: 20, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -8, socialLife: 0, discipline: -5, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Free alternatives',
        consequence: 'World-class teaching',
        benefit: 'Free options available',
      ),

      SpendingScenario(
        id: 'edu_13',
        title: 'Internship in Another City',
        description: 'Unpaid internship, need ₹15,000 for room. Great experience.',
        cost: 15000,
        category: ScenarioCategory.education,
        emoji: '🏢',
        acceptImpact: DecisionImpact(happiness: 15, investments: 30, socialLife: 10, discipline: 25, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -10, investments: -20, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Take internship',
        declineLabel: 'Local opportunities',
        consequence: 'Career boost, big expense',
        benefit: 'Miss opportunity, save money',
      ),

      SpendingScenario(
        id: 'edu_14',
        title: 'Coding Bootcamp',
        description: '3-month coding bootcamp: ₹50,000. Guaranteed placement.',
        cost: 50000,
        category: ScenarioCategory.education,
        emoji: '💻',
        acceptImpact: DecisionImpact(happiness: 15, investments: 35, socialLife: 10, discipline: 30, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -8, investments: -20, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Join bootcamp',
        declineLabel: 'Self-learn',
        consequence: 'Fast track career, huge cost',
        benefit: 'Free but slower progress',
      ),

      SpendingScenario(
        id: 'edu_15',
        title: 'Start Monthly SIP',
        description: 'Financial advisor suggests ₹2,000/month SIP. Build wealth.',
        cost: 2000,
        category: ScenarioCategory.investment,
        emoji: '📊',
        acceptImpact: DecisionImpact(happiness: 10, investments: 30, socialLife: 0, discipline: 25, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -20, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Start SIP',
        declineLabel: 'Spend freely',
        consequence: 'Wealth building starts',
        benefit: 'Lifestyle spending continues',
      ),

      // FASHION & APPEARANCE (10 scenarios)
      SpendingScenario(
        id: 'fashion_1',
        title: 'Limited Edition Sneakers',
        description: 'Sneaker drop: ₹6,000. They\'ll look fire. You have 3 pairs.',
        cost: 6000,
        category: ScenarioCategory.fashion,
        emoji: '👟',
        acceptImpact: DecisionImpact(happiness: 20, investments: -15, socialLife: 10, discipline: -18, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 15, socialLife: 0, discipline: 20, overspendFlag: false),
        acceptLabel: 'Cop them',
        declineLabel: 'Resist',
        consequence: 'Fresh kicks, broke wallet',
        benefit: 'Avoided impulse buy',
      ),

      SpendingScenario(
        id: 'fashion_2',
        title: 'Interview Outfit',
        description: 'Job interview outfit: ₹3,500. Can manage with existing.',
        cost: 3500,
        category: ScenarioCategory.fashion,
        emoji: '👔',
        acceptImpact: DecisionImpact(happiness: 12, investments: 15, socialLife: 5, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -8, socialLife: 0, discipline: 5, overspendFlag: false),
        acceptLabel: 'Buy new',
        declineLabel: 'Use existing',
        consequence: 'Confidence boost, investment',
        benefit: 'Saved money, slight risk',
      ),

      SpendingScenario(
        id: 'fashion_3',
        title: 'Premium Haircut',
        description: 'Premium salon: ₹1,800. Regular costs ₹300.',
        cost: 1800,
        category: ScenarioCategory.fashion,
        emoji: '💇',
        acceptImpact: DecisionImpact(happiness: 15, investments: -10, socialLife: 8, discipline: -12, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Premium',
        declineLabel: 'Regular',
        consequence: 'Great look, 6x price',
        benefit: 'Same result, ₹1500 saved',
      ),

      SpendingScenario(
        id: 'fashion_4',
        title: 'Designer Jacket',
        description: 'Trending jacket: ₹4,500. Winter almost over.',
        cost: 4500,
        category: ScenarioCategory.fashion,
        emoji: '🧥',
        acceptImpact: DecisionImpact(happiness: 15, investments: -15, socialLife: 10, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 15, socialLife: 0, discipline: 18, overspendFlag: false),
        acceptLabel: 'Buy now',
        declineLabel: 'Wait for sale',
        consequence: 'Trendy now, poor timing',
        benefit: 'Save for next season',
      ),

      SpendingScenario(
        id: 'fashion_5',
        title: 'Premium Gym Wear',
        description: 'Gym clothes set: ₹3,000. Current works fine.',
        cost: 3000,
        category: ScenarioCategory.fashion,
        emoji: '👟',
        acceptImpact: DecisionImpact(happiness: 12, investments: -10, socialLife: 5, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Upgrade',
        declineLabel: 'Current is fine',
        consequence: 'Look good, not necessary',
        benefit: 'Function over fashion',
      ),

      SpendingScenario(
        id: 'fashion_6',
        title: 'Skin Care Routine',
        description: 'Premium skincare: ₹4,000. Using basic Nivea (₹200).',
        cost: 4000,
        category: ScenarioCategory.fashion,
        emoji: '🧴',
        acceptImpact: DecisionImpact(happiness: 12, investments: 8, socialLife: 5, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: 5, socialLife: 0, discipline: 8, overspendFlag: false),
        acceptLabel: 'Premium',
        declineLabel: 'Basic',
        consequence: 'Better skin, 20x cost',
        benefit: 'Basic works fine',
      ),

      SpendingScenario(
        id: 'fashion_7',
        title: 'Branded Sunglasses',
        description: 'Prescription sunglasses: ₹5,500. Cheaper ones ₹1,500.',
        cost: 5500,
        category: ScenarioCategory.fashion,
        emoji: '🕶️',
        acceptImpact: DecisionImpact(happiness: 15, investments: -12, socialLife: 8, discipline: -12, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 5, investments: 12, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Branded',
        declineLabel: 'Budget option',
        consequence: 'Style points, luxury price',
        benefit: 'Same function, ₹4k saved',
      ),

      SpendingScenario(
        id: 'fashion_8',
        title: 'Watch Upgrade',
        description: 'Stylish watch: ₹8,000. Phone tells time.',
        cost: 8000,
        category: ScenarioCategory.fashion,
        emoji: '⌚',
        acceptImpact: DecisionImpact(happiness: 15, investments: -15, socialLife: 10, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 15, socialLife: 0, discipline: 20, overspendFlag: false),
        acceptLabel: 'Buy watch',
        declineLabel: 'Phone works',
        consequence: 'Style accessory, expensive',
        benefit: 'Avoided luxury item',
      ),

      SpendingScenario(
        id: 'fashion_9',
        title: 'Perfume Collection',
        description: 'Designer perfume: ₹3,500. Current one works.',
        cost: 3500,
        category: ScenarioCategory.fashion,
        emoji: '🎐',
        acceptImpact: DecisionImpact(happiness: 12, investments: -12, socialLife: 8, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 12, socialLife: 0, discipline: 18, overspendFlag: false),
        acceptLabel: 'Buy perfume',
        declineLabel: 'Current works',
        consequence: 'Smell great, pricey',
        benefit: 'Save money, current is fine',
      ),

      SpendingScenario(
        id: 'fashion_10',
        title: 'Wardrobe Refresh',
        description: 'Fast fashion haul: ₹5,000. Trendy clothes, low quality.',
        cost: 5000,
        category: ScenarioCategory.fashion,
        emoji: '👕',
        acceptImpact: DecisionImpact(happiness: 18, investments: -18, socialLife: 12, discipline: -20, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -5, investments: 18, socialLife: 0, discipline: 22, overspendFlag: false),
        acceptLabel: 'Shop',
        declineLabel: 'Current wardrobe',
        consequence: 'Look trendy, wasteful',
        benefit: 'Sustainable choice, save money',
      ),

      // TECH & GADGETS (10 scenarios)
      SpendingScenario(
        id: 'tech_1',
        title: 'iPhone 15 Upgrade',
        description: 'iPhone 15 on sale: ₹65,000. Current phone works (2 years old).',
        cost: 65000,
        category: ScenarioCategory.tech,
        emoji: '📱',
        acceptImpact: DecisionImpact(happiness: 25, investments: -30, socialLife: 12, discipline: -25, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -10, investments: 30, socialLife: 0, discipline: 30, overspendFlag: false),
        acceptLabel: 'Upgrade',
        declineLabel: 'Wait 1 year',
        consequence: 'Newest tech, massive expense',
        benefit: 'Saved huge, practice patience',
      ),

      SpendingScenario(
        id: 'tech_2',
        title: 'Mechanical Keyboard',
        description: 'Premium keyboard for coding: ₹8,000. Membrane works.',
        cost: 8000,
        category: ScenarioCategory.tech,
        emoji: '⌨️',
        acceptImpact: DecisionImpact(happiness: 15, investments: 5, socialLife: 0, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Buy it',
        declineLabel: 'Current is fine',
        consequence: 'Better typing, pricey luxury',
        benefit: 'Function over aesthetics',
      ),

      SpendingScenario(
        id: 'tech_3',
        title: 'Apple Watch SE',
        description: 'Apple Watch SE: ₹29,000. Phone does same tracking.',
        cost: 29000,
        category: ScenarioCategory.tech,
        emoji: '⌚',
        acceptImpact: DecisionImpact(happiness: 18, investments: -20, socialLife: 10, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 20, socialLife: 0, discipline: 20, overspendFlag: false),
        acceptLabel: 'Buy watch',
        declineLabel: 'Phone enough',
        consequence: 'Convenient, expensive accessory',
        benefit: 'Avoided luxury gadget',
      ),

      SpendingScenario(
        id: 'tech_4',
        title: 'Noise Cancelling Headphones',
        description: 'Sony WH-1000XM5: ₹28,000. Current earphones work.',
        cost: 28000,
        category: ScenarioCategory.tech,
        emoji: '🎧',
        acceptImpact: DecisionImpact(happiness: 20, investments: 5, socialLife: 0, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 15, socialLife: 0, discipline: 20, overspendFlag: false),
        acceptLabel: 'Premium audio',
        declineLabel: 'Current works',
        consequence: 'Focus boost, huge cost',
        benefit: 'Save big, manage distractions',
      ),

      SpendingScenario(
        id: 'tech_5',
        title: 'iPad for Notes',
        description: 'iPad for digital notes: ₹35,000. Paper notebooks work.',
        cost: 35000,
        category: ScenarioCategory.tech,
        emoji: '📱',
        acceptImpact: DecisionImpact(happiness: 15, investments: 10, socialLife: 0, discipline: -15, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 15, socialLife: 0, discipline: 20, overspendFlag: false),
        acceptLabel: 'Digital',
        declineLabel: 'Paper',
        consequence: 'Organized notes, massive cost',
        benefit: 'Paper works, save huge',
      ),

      SpendingScenario(
        id: 'tech_6',
        title: 'Cloud Storage Subscription',
        description: 'Google One 2TB: ₹650/month. Can delete old files.',
        cost: 650,
        category: ScenarioCategory.tech,
        emoji: '☁️',
        acceptImpact: DecisionImpact(happiness: 10, investments: 5, socialLife: 0, discipline: -8, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -3, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Subscribe',
        declineLabel: 'Manage manually',
        consequence: 'Convenience, yearly ₹7800',
        benefit: 'Free but need discipline',
      ),

      SpendingScenario(
        id: 'tech_7',
        title: 'External Monitor',
        description: '27" monitor for productivity: ₹18,000. Laptop screen works.',
        cost: 18000,
        category: ScenarioCategory.tech,
        emoji: '🖥️',
        acceptImpact: DecisionImpact(happiness: 15, investments: 18, socialLife: 0, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -10, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Buy monitor',
        declineLabel: 'Laptop screen',
        consequence: 'Productivity boost, investment',
        benefit: 'Current works, save money',
      ),

      SpendingScenario(
        id: 'tech_8',
        title: 'Tablet for Reading',
        description: 'Kindle Paperwhite: ₹13,000. Phone reading works.',
        cost: 13000,
        category: ScenarioCategory.tech,
        emoji: '📖',
        acceptImpact: DecisionImpact(happiness: 12, investments: 10, socialLife: 0, discipline: 8, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: 5, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Buy Kindle',
        declineLabel: 'Phone reading',
        consequence: 'Better reading experience',
        benefit: 'Phone works, save money',
      ),

      SpendingScenario(
        id: 'tech_9',
        title: 'Portable SSD',
        description: '1TB portable SSD: ₹8,000. Backup important files.',
        cost: 8000,
        category: ScenarioCategory.tech,
        emoji: '💾',
        acceptImpact: DecisionImpact(happiness: 8, investments: 15, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -15, socialLife: 0, discipline: 5, overspendFlag: false),
        acceptLabel: 'Buy SSD',
        declineLabel: 'Cloud backup',
        consequence: 'Data safety, upfront cost',
        benefit: 'Risk data loss, save now',
      ),

      SpendingScenario(
        id: 'tech_10',
        title: 'Wireless Earbuds Upgrade',
        description: 'AirPods Pro: ₹24,000. Current earbuds work.',
        cost: 24000,
        category: ScenarioCategory.tech,
        emoji: '🎧',
        acceptImpact: DecisionImpact(happiness: 18, investments: -18, socialLife: 8, discipline: -18, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: 0, investments: 18, socialLife: 0, discipline: 22, overspendFlag: false),
        acceptLabel: 'Buy AirPods',
        declineLabel: 'Current works',
        consequence: 'Premium audio, huge cost',
        benefit: 'Current works fine, save big',
      ),

      // TRANSPORT (5 scenarios)
      SpendingScenario(
        id: 'transport_1',
        title: 'Buy Used Bike',
        description: 'Friend selling bike: ₹35,000. Saves ₹2,000/month transport.',
        cost: 35000,
        category: ScenarioCategory.transport,
        emoji: '🏍️',
        acceptImpact: DecisionImpact(happiness: 15, investments: 25, socialLife: 5, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -15, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Buy bike',
        declineLabel: 'Public transport',
        consequence: 'Long-term savings, big upfront',
        benefit: 'No maintenance costs',
      ),

      SpendingScenario(
        id: 'transport_2',
        title: 'Split Uber Daily',
        description: 'Split Uber daily: ₹150. Bus costs ₹30 but 1 hour extra.',
        cost: 150,
        category: ScenarioCategory.transport,
        emoji: '🚗',
        acceptImpact: DecisionImpact(happiness: 12, investments: -10, socialLife: 8, discipline: -12, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Split Uber',
        declineLabel: 'Take bus',
        consequence: 'Save time, ₹3600/month gone',
        benefit: 'Save ₹3600/month, lose 30 hrs',
      ),

      SpendingScenario(
        id: 'transport_3',
        title: 'Monthly Parking Pass',
        description: 'College parking: ₹2,000/month. Bus pass ₹500/month.',
        cost: 2000,
        category: ScenarioCategory.transport,
        emoji: '🅿️',
        acceptImpact: DecisionImpact(happiness: 10, investments: -12, socialLife: 0, discipline: -10, overspendFlag: true),
        declineImpact: DecisionImpact(happiness: -8, investments: 12, socialLife: 0, discipline: 15, overspendFlag: false),
        acceptLabel: 'Park',
        declineLabel: 'Bus',
        consequence: 'Convenience, ₹1500/month extra',
        benefit: 'Save ₹18k/year, lose time',
      ),

      SpendingScenario(
        id: 'transport_4',
        title: 'Bike Service Maintenance',
        description: 'Bike service: ₹3,000. Running fine but might break soon.',
        cost: 3000,
        category: ScenarioCategory.transport,
        emoji: '🔧',
        acceptImpact: DecisionImpact(happiness: 8, investments: 15, socialLife: 0, discipline: 18, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -15, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Service now',
        declineLabel: 'Wait',
        consequence: 'Preventive care, upfront cost',
        benefit: 'Risk breakdown, save now',
      ),

      SpendingScenario(
        id: 'transport_5',
        title: 'Fuel Efficient Bike',
        description: 'Trade for fuel-efficient bike: ₹25,000. Saves ₹1,000/month.',
        cost: 25000,
        category: ScenarioCategory.transport,
        emoji: '🏍️',
        acceptImpact: DecisionImpact(happiness: 12, investments: 25, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -10, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Upgrade',
        declineLabel: 'Keep current',
        consequence: 'Pays off in 2 years',
        benefit: 'No upfront cost',
      ),

      // HEALTH & EMERGENCY (10 scenarios)
      SpendingScenario(
        id: 'health_1',
        title: 'Laptop Screen Repair',
        description: 'Screen cracked: ₹12,000 repair. Need for college work.',
        cost: 12000,
        category: ScenarioCategory.emergency,
        emoji: '💻',
        acceptImpact: DecisionImpact(happiness: 10, investments: 15, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -15, investments: -20, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Repair it',
        declineLabel: 'Delay',
        consequence: 'Functional, unplanned expense',
        benefit: 'Risk college work, saved money',
      ),

      SpendingScenario(
        id: 'health_2',
        title: 'Medical Check-up',
        description: 'Persistent headaches. Doctor + tests: ₹3,000.',
        cost: 3000,
        category: ScenarioCategory.health,
        emoji: '🏥',
        acceptImpact: DecisionImpact(happiness: 10, investments: 20, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -10, investments: -25, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Get checked',
        declineLabel: 'Self-medicate',
        consequence: 'Peace of mind, cost involved',
        benefit: 'Risky, might worsen',
      ),

      SpendingScenario(
        id: 'health_3',
        title: 'Phone Insurance',
        description: 'Annual phone insurance: ₹3,500. Covers damage/theft.',
        cost: 3500,
        category: ScenarioCategory.emergency,
        emoji: '📱',
        acceptImpact: DecisionImpact(happiness: 8, investments: 10, socialLife: 0, discipline: 12, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -3, investments: -10, socialLife: 0, discipline: 10, overspendFlag: false),
        acceptLabel: 'Insure',
        declineLabel: 'Risk it',
        consequence: 'Peace of mind, yearly cost',
        benefit: 'Save money, self-insure',
      ),

      SpendingScenario(
        id: 'health_4',
        title: 'Dental Cleaning',
        description: 'Annual dental cleaning: ₹2,000. No pain currently.',
        cost: 2000,
        category: ScenarioCategory.health,
        emoji: '🦷',
        acceptImpact: DecisionImpact(happiness: 8, investments: 18, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -15, socialLife: 0, discipline: -10, overspendFlag: false),
        acceptLabel: 'Preventive care',
        declineLabel: 'Skip',
        consequence: 'Prevent future issues',
        benefit: 'Risk bigger problems later',
      ),

      SpendingScenario(
        id: 'health_5',
        title: 'Emergency Fund Start',
        description: 'Put ₹10,000 in emergency fund. Want to invest instead.',
        cost: 10000,
        category: ScenarioCategory.investment,
        emoji: '💰',
        acceptImpact: DecisionImpact(happiness: 8, investments: 30, socialLife: 0, discipline: 30, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -20, socialLife: 0, discipline: -20, overspendFlag: false),
        acceptLabel: 'Save',
        declineLabel: 'Invest',
        consequence: 'Financial safety net',
        benefit: 'Higher returns but risky',
      ),

      SpendingScenario(
        id: 'health_6',
        title: 'AC Gas Refill',
        description: 'AC needs gas: ₹2,500. Summer coming but still runs.',
        cost: 2500,
        category: ScenarioCategory.emergency,
        emoji: '❄️',
        acceptImpact: DecisionImpact(happiness: 10, investments: 10, socialLife: 0, discipline: 15, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -10, socialLife: 0, discipline: -8, overspendFlag: false),
        acceptLabel: 'Fix now',
        declineLabel: 'Wait',
        consequence: 'Ready for summer',
        benefit: 'May need urgent fix later',
      ),

      SpendingScenario(
        id: 'health_7',
        title: 'Eye Check-up & Glasses',
        description: 'Struggling to see. Eye test + glasses: ₹4,000.',
        cost: 4000,
        category: ScenarioCategory.health,
        emoji: '👓',
        acceptImpact: DecisionImpact(happiness: 15, investments: 20, socialLife: 0, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -10, investments: -15, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Get glasses',
        declineLabel: 'Delay',
        consequence: 'See clearly, necessary cost',
        benefit: 'Strain eyes, risky',
      ),

      SpendingScenario(
        id: 'health_8',
        title: 'Mental Health Therapy',
        description: 'Feeling anxious. Therapy session: ₹2,000.',
        cost: 2000,
        category: ScenarioCategory.health,
        emoji: '🧠',
        acceptImpact: DecisionImpact(happiness: 20, investments: 25, socialLife: 5, discipline: 20, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -15, investments: -20, socialLife: 0, discipline: -15, overspendFlag: false),
        acceptLabel: 'Book session',
        declineLabel: 'Handle alone',
        consequence: 'Mental health investment',
        benefit: 'Struggle alone, risky',
      ),

      SpendingScenario(
        id: 'health_9',
        title: 'Vitamins & Supplements',
        description: 'Multivitamin course: ₹1,500. Feeling low energy.',
        cost: 1500,
        category: ScenarioCategory.health,
        emoji: '💊',
        acceptImpact: DecisionImpact(happiness: 10, investments: 12, socialLife: 0, discipline: 10, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: -5, investments: -8, socialLife: 0, discipline: -5, overspendFlag: false),
        acceptLabel: 'Buy vitamins',
        declineLabel: 'Natural diet',
        consequence: 'Health boost, investment',
        benefit: 'Natural food cheaper',
      ),

      SpendingScenario(
        id: 'health_10',
        title: 'Health Insurance',
        description: 'Annual health insurance: ₹8,000. You\'re young, healthy.',
        cost: 8000,
        category: ScenarioCategory.health,
        emoji: '🏥',
        acceptImpact: DecisionImpact(happiness: 10, investments: 30, socialLife: 0, discipline: 30, overspendFlag: false),
        declineImpact: DecisionImpact(happiness: 0, investments: -25, socialLife: 0, discipline: -20, overspendFlag: false),
        acceptLabel: 'Get insured',
        declineLabel: 'Risk it',
        consequence: 'Financial protection, smart',
        benefit: 'Young now, risky long-term',
      ),
    ];
  }

  static List<SpendingScenario> getRandomScenarios({int count = 15}) {
    final allScenarios = getAllScenarios();
    final shuffled = List<SpendingScenario>.from(allScenarios)..shuffle(Random());
    return shuffled.take(count).toList();
  }
}
